# BÁO CÁO MÔ TẢ VÀ THỐNG KÊ DỮ LIỆU OPENFDA
- **Họ và tên:** Nguyễn Văn Phát
- **MSSV:** 24521314
- **Môn học:** Học máy Thống kê (DS102)

## 1. Giới thiệu bộ dữ liệu
- Bộ dữ liệu được thu thập từ **OpenFDA Drug Event API** (`https://api.fda.gov/drug/event.json`), ghi nhận thông tin về các biến cố bất lợi khi sử dụng thuốc.
- Dữ liệu khi thu thập có 9 columns và 10000 rows

**Ý nghĩa các trường thông tin:**
- `Age`: Tuổi của bệnh nhân.
- `Weight_kg`: Cân nặng của bệnh nhân (kg).
- `Sex`: Giới tính bệnh nhân (1: Nam, 2: Nữ, 0: Không xác định).
- `Num_Drugs`: Tổng số lượng thuốc bệnh nhân đang dùng.
- `Indication`: Chỉ định điều trị của thuốc.
- `Reaction`: Phản ứng phụ hoặc biến cố bất lợi gặp phải.
- `Hospitalization`: Biến cố gây nhập viện (1: Có, 0: Không).
- `Death`: Biến cố dẫn đến tử vong (1: Có, 0: Không).
- `Disabling`: Biến cố gây tàn tật, suy giảm chức năng (1: Có, 0: Không).

## 2. Đọc dữ liệu và xem tổng quan

In [1]:
import pandas as pd

df = pd.read_csv("openfda_drug_events.csv")
print("Kích thước tập dữ liệu:", df.shape)
df.head(100)

Kích thước tập dữ liệu: (10000, 9)

,Age,Weight_kg,Sex,Num_Drugs,Indication,Reaction,Hospitalization,Death,Disabling
0,43,41.80,2.0,6,CRYOPYRIN ASSOCIATED PERIODIC SYNDROME,Pneumonia,1,0,0
1,46,65.50,1.0,3,SYSTEMIC LUPUS ERYTHEMATOSUS,Angioedema,0,0,0
2,59,57.80,2.0,8,SYSTEMIC LUPUS ERYTHEMATOSUS,Tuberculosis of central nervous system,1,1,0
3,73,57.00,2.0,1,ATRIAL FIBRILLATION,Fall,0,0,0
4,79,61.00,2.0,22,PAIN,Diarrhoea,1,0,0
...,...,...,...,...,...,...,...,...,...
95,34,55.84,1.0,3,EPILEPSY,Convulsion,0,0,0
96,80,63.04,2.0,4,NaN,Haemorrhage,0,0,0
97,48,100.00,1.0,6,HEPATITIS C,Injection site rash,0,0,0
98,59,82.54,2.0,6,MYELOFIBROSIS,Epistaxis,0,0,0
99,39,120.31,2.0,4,CONTRACEPTION,Anaphylactic reaction,0,0,0

## 3. Kiểu dữ liệu

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              10000 non-null  int64
 1   Weight_kg        10000 non-null  float64
 2   Sex              9978 non-null   float64
 3   Num_Drugs        10000 non-null  int64
 4   Indication       8857 non-null   str
 5   Reaction         10000 non-null  str
 6   Hospitalization  10000 non-null  int64
 7   Death            10000 non-null  int64
 8   Disabling        10000 non-null  int64
dtypes: float64(2), int64(5), str(2)
memory usage: 703.3 KB

In [5]:
# Kiểm tra dòng thiếu dữ liệu 
print("Số dòng có dữ liệu thiếu:", df.isnull().any(axis=1).sum())

df.isnull().sum()

Số dòng có dữ liệu thiếu: 1161

Age                   0
Weight_kg             0
Sex                  22
Num_Drugs             0
Indication         1143
Reaction              0
Hospitalization       0
Death                 0
Disabling             0
dtype: int64

In [3]:
# Kiểm tra số dòng trùng lặp
print("Số dòng bị trùng lặp:", df.duplicated().sum())

Số dòng bị trùng lặp: 160

## 4. Thống kê mô tả (Descriptive Statistics)
Thống kê các chỉ số cơ bản (trung bình, độ lệch chuẩn, min, max, tứ phân vị) cho các thuộc tính định lượng.

In [4]:
df.describe()

,Age,Weight_kg,Sex,Num_Drugs,Hospitalization,Death,Disabling
count,10000.000000,10000.000000,9978.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,104.858900,74.449827,1.619763,5.256900,0.333400,0.069100,0.057600
std,1086.521745,24.733563,0.492642,6.243236,0.473357,0.260638,0.241843
min,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
25%,41.000000,60.000000,1.000000,2.000000,0.000000,0.000000,0.000000
50%,57.000000,72.580000,2.000000,3.000000,0.000000,0.000000,0.000000
75%,69.000000,87.507500,2.000000,7.000000,1.000000,0.000000,0.000000
max,32654.000000,320.000000,2.000000,172.000000,2.000000,2.000000,2.000000